### ISSUE TITLE
Windows support for Altair Saver via NodeJS backend

### ISSUE THREAD

**Issue by jawnsy** [altair-viz/altair_saver#67]
Hi there,

I tried to install and configure Altair Saver using the NodeJS backend on Windows 10, but I'm getting an error when trying to save from JupyterLab running via Miniconda on Git Bash. I have NodeJS installed and I'm able to install the vega-lite and vega-cli packages. This puts a bunch of scripts in my ~/.npm-packages/bin folder, so far so good:

```
$ ls ~/.npm-packages/bin
vg2pdf      vg2png      vg2svg      vl2pdf      vl2png      vl2svg      vl2vg
vg2pdf.cmd  vg2png.cmd  vg2svg.cmd  vl2pdf.cmd  vl2png.cmd  vl2svg.cmd  vl2vg.cmd
```

I have a simple Altair Chart that I'm trying to save (it displays fine inside JupyterLab), and it returns this error message and stack trace:

```
(not in PATH env variable)
TypeError: Cannot read property 'getContext' of null
    at resize (C:\Users\Jonathan.Yu\AppData\Local\Yarn\Data\global\node_modules\vega-scenegraph\build\vega-scenegraph.js:3678:28)
    at CanvasRenderer.prototype$6.resize (C:\Users\Jonathan.Yu\AppData\Local\Yarn\Data\global\node_modules\vega-scenegraph\build\vega-scenegraph.js:3727:5)
    at CanvasRenderer.prototype$4.initialize (C:\Users\Jonathan.Yu\AppData\Local\Yarn\Data\global\node_modules\vega-scenegraph\build\vega-scenegraph.js:3307:17)
    at CanvasRenderer.prototype$6.initialize (C:\Users\Jonathan.Yu\AppData\Local\Yarn\Data\global\node_modules\vega-scenegraph\build\vega-scenegraph.js:3722:28)
    at initializeRenderer (C:\Users\Jonathan.Yu\AppData\Local\Yarn\Data\global\node_modules\vega-view\build\vega-view.js:649:8)
    at renderHeadless (C:\Users\Jonathan.Yu\AppData\Local\Yarn\Data\global\node_modules\vega-view\build\vega-view.js:772:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async View.renderToCanvas [as toCanvas] (C:\Users\Jonathan.Yu\AppData\Local\Yarn\Data\global\node_modules\vega-view\build\vega-view.js:807:15)
```

I installed using `yarn global` so that might be part of the problem? I'd be happy to debug and contribute a patch but would need a pointer to the relevant bits of code.

**Comment by jawnsy** [comment]
Okay, so one problem is that I missed the `canvas` dependency, duh. I've installed it and verified that node is able to find it:

```
~/AppData/Local/Yarn/Data/global/node_modules/canvas $ yarn install
yarn install v1.7.0
warning ..\..\package.json: No license field
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
⠁ (node:28868) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsa
fe(), or Buffer.from() methods instead.
warning dtslint > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning mocha > mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to u
se Promises in 1.x.)
warning standard > eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...

success Saved lockfile.
$ node-pre-gyp install --fallback-to-build
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@12.16.3 | win32 | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "C:\Users\Jonathan.Yu\AppData\Local\Yarn\Data\global\node_modules\canvas\build\Release\canvas.node" (not found)
node-pre-gyp http GET https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v72-win32-unknown-x64.tar.gz
node-pre-gyp http 200 https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v72-win32-unknown-x64.tar.gz
node-pre-gyp info install unpacking Release/
node-pre-gyp info install unpacking Release/canvas.exp
node-pre-gyp info install unpacking Release/canvas.ilk
node-pre-gyp info install unpacking Release/canvas.lib
node-pre-gyp info install unpacking Release/canvas.node
node-pre-gyp info install unpacking Release/canvas.pdb
node-pre-gyp info install unpacking Release/libbz2-1.dll
node-pre-gyp info install unpacking Release/libcairo-2.dll
node-pre-gyp info install unpacking Release/libcroco-0.6-3.dll
node-pre-gyp info install unpacking Release/libdatrie-1.dll
node-pre-gyp info install unpacking Release/libexpat-1.dll
node-pre-gyp info install unpacking Release/libffi-6.dll
node-pre-gyp info install unpacking Release/libfontconfig-1.dll
node-pre-gyp info install unpacking Release/libfreetype-6.dll
node-pre-gyp info install unpacking Release/libfribidi-0.dll
node-pre-gyp info install unpacking Release/libgcc_s_seh-1.dll
node-pre-gyp info install unpacking Release/libgdk_pixbuf-2.0-0.dll
node-pre-gyp info install unpacking Release/libgif-7.dll
node-pre-gyp info install unpacking Release/libgio-2.0-0.dll
node-pre-gyp info install unpacking Release/libglib-2.0-0.dll
node-pre-gyp info install unpacking Release/libgmodule-2.0-0.dll
node-pre-gyp info install unpacking Release/libgobject-2.0-0.dll
node-pre-gyp info install unpacking Release/libgraphite2.dll
node-pre-gyp info install unpacking Release/libharfbuzz-0.dll
node-pre-gyp info install unpacking Release/libiconv-2.dll
node-pre-gyp info install unpacking Release/libintl-8.dll
node-pre-gyp info install unpacking Release/libjpeg-8.dll
node-pre-gyp info install unpacking Release/liblzma-5.dll
node-pre-gyp info install unpacking Release/libpango-1.0-0.dll
node-pre-gyp info install unpacking Release/libpangocairo-1.0-0.dll
node-pre-gyp info install unpacking Release/libpangoft2-1.0-0.dll
node-pre-gyp info install unpacking Release/libpangowin32-1.0-0.dll
node-pre-gyp info install unpacking Release/libpcre-1.dll
node-pre-gyp info install unpacking Release/libpixman-1-0.dll
node-pre-gyp info install unpacking Release/libpng16-16.dll
node-pre-gyp info install unpacking Release/librsvg-2-2.dll
node-pre-gyp info install unpacking Release/libstdc++-6.dll
node-pre-gyp info install unpacking Release/libthai-0.dll
node-pre-gyp info install unpacking Release/libwinpthread-1.dll
node-pre-gyp info install unpacking Release/libxml2-2.dll
node-pre-gyp info install unpacking Release/obj/
node-pre-gyp info install unpacking Release/obj/canvas/
node-pre-gyp info install unpacking Release/obj/canvas/Backend.obj
node-pre-gyp info install unpacking Release/obj/canvas/Backends.obj
node-pre-gyp info install unpacking Release/obj/canvas/BMPParser.obj
node-pre-gyp info install unpacking Release/obj/canvas/Canvas.obj
node-pre-gyp info install unpacking Release/obj/canvas/canvas.tlog/
node-pre-gyp info install unpacking Release/obj/canvas/canvas.tlog/canvas.lastbuildstate
node-pre-gyp info install unpacking Release/obj/canvas/canvas.tlog/canvas.write.1u.tlog
node-pre-gyp info install unpacking Release/obj/canvas/canvas.tlog/CL.1904.write.1.tlog
node-pre-gyp info install unpacking Release/obj/canvas/canvas.tlog/CL.command.1.tlog
node-pre-gyp info install unpacking Release/obj/canvas/canvas.tlog/CL.read.1.tlog
node-pre-gyp info install unpacking Release/obj/canvas/canvas.tlog/link.command.1.tlog
node-pre-gyp info install unpacking Release/obj/canvas/canvas.tlog/link.read.1.tlog
node-pre-gyp info install unpacking Release/obj/canvas/canvas.tlog/link.write.1.tlog
node-pre-gyp info install unpacking Release/obj/canvas/CanvasGradient.obj
node-pre-gyp info install unpacking Release/obj/canvas/CanvasPattern.obj
node-pre-gyp info install unpacking Release/obj/canvas/CanvasRenderingContext2d.obj
node-pre-gyp info install unpacking Release/obj/canvas/closure.obj
node-pre-gyp info install unpacking Release/obj/canvas/color.obj
node-pre-gyp info install unpacking Release/obj/canvas/Image.obj
node-pre-gyp info install unpacking Release/obj/canvas/ImageBackend.obj
node-pre-gyp info install unpacking Release/obj/canvas/ImageData.obj
node-pre-gyp info install unpacking Release/obj/canvas/init.obj
node-pre-gyp info install unpacking Release/obj/canvas/PdfBackend.obj
node-pre-gyp info install unpacking Release/obj/canvas/register_font.obj
node-pre-gyp info install unpacking Release/obj/canvas/SvgBackend.obj
node-pre-gyp info install unpacking Release/obj/canvas/vcpkg.applocal.log
node-pre-gyp info install unpacking Release/obj/canvas/win_delay_load_hook.obj
node-pre-gyp info install unpacking Release/zlib1.dll
node-pre-gyp info tarball done parsing tarball
[canvas] Success: "C:\Users\Jonathan.Yu\AppData\Local\Yarn\Data\global\node_modules\canvas\build\Release\canvas.node" is installed via remote
node-pre-gyp info ok
Done in 31.76s.
(base) 19:26 Jonathan.Yu@JYU3 ~/AppData/Local/Yarn/Data/global/node_modules/canvas $ node
Welcome to Node.js v12.16.3.
Type ".help" for more information.
> require('canvas')
{
  Canvas: [Function: Canvas] { _registerFont: [Function: _registerFont] },
  Context2d: [Function: CanvasRenderingContext2D],
  CanvasRenderingContext2D: [Function: CanvasRenderingContext2D],
  CanvasGradient: [Function: CanvasGradient],
  CanvasPattern: [Function: CanvasPattern],
  Image: [Function: Image] { MODE_IMAGE: 1, MODE_MIME: 2 },
  ImageData: [Function: ImageData],
  PNGStream: [Function: PNGStream],
  PDFStream: [Function: PDFStream],
  JPEGStream: [Function: JPEGStream],
  DOMMatrix: [Function: DOMMatrix] {
    fromMatrix: [Function],
    fromFloat32Array: [Function],
    fromFloat64Array: [Function]
  },
  DOMPoint: [Function: DOMPoint],
  registerFont: [Function: registerFont],
  parseFont: [Function],
  createCanvas: [Function: createCanvas],
  createImageData: [Function: createImageData],
  loadImage: [Function: loadImage],
  backends: {
    ImageBackend: [Function: ImageBackend],
    PdfBackend: [Function: PdfBackend],
    SvgBackend: [Function: SvgBackend]
  },
  version: '2.6.1',
  cairoVersion: '1.16.0',
  jpegVersion: '8',
  gifVersion: '5.2.1',
  freetypeVersion: '2.10.1'
}
```

However, vg2png just outputs an empty image:

```
$ vg2png test.vg.json output.png
$ ls -al output.png
-rw-r--r-- 1 Jonathan.Yu 1049089 0 Apr 29 19:30 output.png
```

So after messing around a little, I found that if I manually use `vl2vg` and then `vg2png` then the output is produced correctly. So I think there's an issue with `vl2png` which causes it to be unable to handle spaces in paths

**Comment by jakevdp** [comment]
The first error looks like the same one people are hitting in https://github.com/altair-viz/altair_saver/issues/13

As for the second error: it's an issue with system paths visible to npm tools, and is why altair_saver avoids using the ``vl2*`` executables in favor of ``vl2vg``+``vg2*``

**Comment by jawnsy** [comment]
Ah, sorry, I didn't realize this was a duplicate, thanks for the pointer! I have no idea what fixed things for me, but somehow everything is working for me now. It's possible that the `npm config set ignore-scripts true` fixed it? Ugh I hate computers
