### ISSUE TITLE
is `alt.renderers.enable('altair_saver', ['vega-lite', 'png'])` on README outdated?

### ISSUE THREAD

**Issue by zyxue** [altair-viz/altair_saver#76]
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-53-092c93936f9f> in <module>
----> 1 altair.renderers.enable('altair_saver', ['vega-lite', 'png'])

TypeError: enable() takes from 1 to 2 positional arguments but 3 were given
```

https://github.com/altair-viz/altair/blob/582b590a29dfbfc06aad27be79371f98a763a0aa/altair/utils/plugin_registry.py#L156

**Comment by jakevdp** [comment]
Maybe it needs to be passed as a keyword argument?

**Comment by zyxue** [comment]
what's the keyword?
tried
```
>>> altair.renderers.enable('altair_saver', fmts=['vega-lite', 'png'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/lib/python3.8/site-packages/altair/utils/plugin_registry.py", line 177, in enable
    return PluginEnabler(self, name, **options)
  File "/path/to/lib/python3.8/site-packages/altair/utils/plugin_registry.py", line 27, in __init__
    self.registry._enable(name, **options)
  File "/path/to/lib/python3.8/site-packages/altair/utils/plugin_registry.py", line 142, in _enable
    ep = entrypoints.get_single(self.entry_point_group, name)
  File "/path/to/lib/python3.8/site-packages/entrypoints.py", line 217, in get_single
    raise NoSuchEntryPoint(group, name)
entrypoints.NoSuchEntryPoint: No 'altair_saver' entry point found in group 'altair.vegalite.v4.renderer'
```

**Comment by jakevdp** [comment]
The `NoSuchEntryPoint` error suggests that the `altair_saver` package is not installed in the environment where you're trying to use it.

**Comment by zyxue** [comment]
I see, thanks. it's unclear what the keyword should be, and how it works. All these seem to run

```
>>> import altair
>>> altair.renderers.enable('altair_saver', abc=['vega-lite', 'png'])
RendererRegistry.enable('altair_saver')
>>> altair.renderers.enable('altair_saver', xyz=['vega-lite', 'png'])
RendererRegistry.enable('altair_saver')
>>> altair.renderers.enable('altair_saver', fmts=['vega-lite', 'png'])
RendererRegistry.enable('altair_saver')
```

**Comment by jakevdp** [comment]
I think `fmts` is the correct argument. I suspect the others will fail when you try displaying a chart.

**Comment by zyxue** [comment]
I see. you're right.

Is 

```
altair.renderers.enable('altair_saver', fmts=['svg'])
```
the same as
```
altair.renderers.enable('svg`)
```?

Both seem to work

**Comment by jakevdp** [comment]
Yes, they do the same thing. `altair_saver` provides a superset of the functionality of altair's built-in renderers.

**Comment by jakevdp** [comment]
(and under the hood, `altair.renderers.enable('svg')` is using `altair_saver`)

**Comment by zyxue** [comment]
I find it a bit confusing. How could I better understand it given that `altair_saver` is the name of a saver while `svg` is the name of a format? How is it structured under the hood?
