### ISSUE TITLE
SyntaxError when saving as png

### ISSUE THREAD

**Issue by kekeblom** [altair-viz/altair_saver#80]
I just tried saving a simple scatter plot as a png. I receive the following error:
```
/home/user/miniconda3/envs/track/lib/vega-cli/node_modules/vega-dataflow/build/vega-dataflow.js:43
  async function asyncCallback(df, callback) {
        ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/user/miniconda3/envs/track/lib/vega-cli/node_modules/vega/build/vega-node.js:6:20)
```

I installed Altair Saver using `conda install altair_saver` as instructed in the docs. I'm guessing it's somehow related to the version of Nodejs and the code using syntax that is not supported by that version.

If it's any help, when I run `node --version` I get `v6.13.1`.

**Comment by jakevdp** [comment]
Async funcitons are [not supported in older nodeJS versions](http://kangax.github.io/compat-table/esnext/). You'll need to update nodeJS to use this functionality.

**Comment by kekeblom** [comment]
Deleting the conda package, installing the packages through pip and manually installing the node dependencies seems to solve the issue.
